name: Deploy ProXperty_backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Production Docker Image
        run: sudo docker build -f Dockerfile.prod -t proxperty/proxperty_backend:latest .

      - name: Push Image to Docker Hub
        run: sudo docker push proxperty/proxperty_backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull latest image
        run: sudo docker pull proxperty/proxperty_backend:latest

      - name: Stop & remove old container
        run: sudo docker rm -f proxperty_backend || true

      - name: Run new container
        run: |
          sudo docker run -d \
            --name proxperty_backend \
            -p 3500:3500 \
            --restart unless-stopped \
            -e NODE_ENV=production \
            -e MONGO_URI='${{ secrets.MONGO_URI }}' \
            -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
            -e AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' \
            -e AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
            -e AWS_REGION='${{ secrets.AWS_REGION }}' \
            -e AWS_S3_BUCKET_NAME='${{ secrets.AWS_S3_BUCKET_NAME }}' \
            proxperty/proxperty_backend:latest
